# Generated by Django 5.2.5 on 2025-10-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=12, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=12, unique=True)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('observaciones', models.TextField(max_length=500)),
                ('tipo_parto', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.doctor')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.madre')),
            ],
        ),
        migrations.CreateModel(
            name='Nacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('sexo', models.CharField(max_length=20)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.parto')),
            ],
        ),
    ]
